name: Update Blog Metadata

on:
  push:
    paths:
      - 'posts/**'

jobs:
  generate-metadata:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Generate Metadata
      run: |
        # 安装依赖（如果需要）
        sudo apt-get install jq

        # 生成元数据
        echo "正在生成元数据..."
        cd posts
        echo '[' > posts.json
        ls -1v *.txt | while read file; do
            filename="${file%.*}"
            date="$(echo $filename | cut -d'-' -f1-3)"
            title="$(echo $filename | cut -d'-' -f4- | tr '-' ' ')"
            echo "{ \"filename\": \"$filename\", \"title\": \"$title\", \"date\": \"$date\" }" >> posts.json
            echo "," >> posts.json
        done
        sed -i '$ d' posts.json # 删除最后一个逗号
        echo ']' >> posts.json

        # 提交变更
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add posts.json
        git commit -m "Auto-update posts metadata"
        git push
